/**
 * `npm run harness:check` - repo-local gate runner for P3.
 *
 * WHAT THIS IS NOT
 * ----------------
 * The official Agent Harness scored evaluation for this problem is **deferred until all three
 * MVPs exist** (see `action.md`). `loops evaluate` is documented as returning an evaluator
 * *prompt* that a human or agent then executes by hand; it is not a pass/fail runner and emits
 * no machine-readable criterion results.
 *
 * So this script computes **no score** and claims **nothing** about the scored criteria. It runs
 * the deterministic, repository-local gates that back the claims made in the docs, and writes the
 * observed result to `docs/harness-run-log.md`. A green run here means "the local checks pass",
 * not "the scored evaluation passes".
 *
 * Usage:
 *   npm run harness:check
 *   npm run harness:check -- --no-log    # do not rewrite docs/harness-run-log.md
 */

import { spawn } from 'node:child_process'
import { existsSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'
import { platform } from 'node:process'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolvePath(here, '..')
const logPath = join(repoRoot, 'docs', 'harness-run-log.md')
const writeLog = !process.argv.slice(2).includes('--no-log')

const npm = platform === 'win32' ? 'npm.cmd' : 'npm'

/** Gates that back specific claims in the docs. Each one is a real command, not a claim. */
const GATES = [
  {
    id: 'typecheck',
    command: [npm, 'run', 'typecheck'],
    backs: 'The TypeScript sources, the agent services and all scripts compile under strict settings.',
  },
  {
    id: 'test',
    command: [npm, 'run', 'test'],
    backs:
      'Criteria 1-6 and 8: endpoint policy, malformed-record skipping, membership enforcement, forward timeout, explicit no-agent response, recorded cases, and the no-literal-list check.',
  },
  {
    id: 'check:secrets',
    command: [npm, 'run', 'check:secrets'],
    backs: 'Criterion 9: no credential-shaped content in tracked files, including authenticated URLs.',
  },
  {
    id: 'check:docs',
    command: [npm, 'run', 'check:docs'],
    backs: 'Every `file:line` reference in the docs still resolves, so the code pointers are claims a reviewer can check.',
  },
  {
    id: 'build',
    command: [npm, 'run', 'build'],
    backs: 'The production browser bundle builds, and it contains no model key or RPC URL.',
  },
]

/**
 * Documents a reviewer is entitled to find. Missing files fail the run.
 *
 * `docs/harness-run-log.md` is deliberately NOT in this list: this script writes that file at
 * the end of the run, so requiring it beforehand would fail the first run of a fresh clone for
 * no real reason.
 */
const REQUIRED_DOCS = [
  ['README.md', 'setup, flow, record keys, discovery, demo, limitations'],
  ['docs/problem-statement.md', 'the problem and its nine scored checks, restated here'],
  ['docs/agent-record-format.md', 'the ENS text-record format and its bounds'],
  ['docs/discovery-strategy.md', 'the reproducible namespace strategy and its documented limits'],
  ['docs/routing-cases.md', 'the recorded routing cases with expected agent or expected no-agent'],
  ['docs/acceptance-checklist.md', 'per-criterion status with honest wording'],
  ['dev-registry/README.md', 'what the development fallback is and is not'],
]

function run(command) {
  return new Promise((resolve) => {
    const startedAt = Date.now()
    const child = spawn(command[0], command.slice(1), {
      cwd: repoRoot,
      stdio: 'inherit',
      shell: platform === 'win32',
    })
    child.on('error', (error) => resolve({ ok: false, durationMs: Date.now() - startedAt, error: error.message }))
    child.on('close', (code) =>
      resolve({ ok: code === 0, durationMs: Date.now() - startedAt, code: code ?? -1 }),
    )
  })
}

function rule(char = '-') {
  return char.repeat(78)
}

function renderLog(results, docResults, startedAt, durationMs) {
  const out = []
  const failed = results.filter((r) => !r.ok).length
  const missingDocs = docResults.filter((d) => !d.exists).length

  out.push('# P3 local gate log')
  out.push('')
  out.push('> Generated by `npm run harness:check` (`scripts/harness-check.mjs`).')
  out.push('>')
  out.push('> **This is a repo-local record, not a score.** The official Agent Harness scored')
  out.push('> evaluation for `ens-agent-router` has not been run: it is deferred until all three')
  out.push('> MVPs exist (see `action.md`). `loops evaluate` returns an evaluator *prompt* to be')
  out.push('> executed by hand, not a pass/fail result, so nothing here may be read as a scored')
  out.push('> criterion outcome. `docs/acceptance-checklist.md` states the per-criterion status using')
  out.push('> the local evidence that exists.')
  out.push('')
  out.push(rule)
  out.push('')
  out.push(`- Run started: \`${startedAt}\``)
  out.push(`- Duration: ${(durationMs / 1000).toFixed(1)} s`)
  out.push(`- Gates: ${results.length - failed} of ${results.length} passed`)
  out.push(`- Required documents: ${docResults.length - missingDocs} of ${docResults.length} present`)
  out.push('')
  out.push(rule)
  out.push('')
  out.push('## Gates')
  out.push('')
  out.push('| Gate | Result | Time | What it backs |')
  out.push('| --- | --- | --- | --- |')
  for (const result of results) {
    out.push(
      `| \`${result.id}\` | ${result.ok ? '**pass**' : '**FAIL**'} | ${(result.durationMs / 1000).toFixed(1)} s | ${result.backs} |`,
    )
  }
  out.push('')
  out.push(rule)
  out.push('')
  out.push('## Required documents')
  out.push('')
  out.push('| File | Present | Why it is required |')
  out.push('| --- | --- | --- |')
  for (const doc of docResults) {
    out.push(`| \`${doc.path}\` | ${doc.exists ? 'yes' : '**MISSING**'} | ${doc.why} |`)
  }
  out.push('')
  out.push(rule)
  out.push('')
  out.push('## Deliberately not covered here')
  out.push('')
  out.push('- **A scored harness evaluation.** Deferred on purpose; see the note above.')
  out.push('- **Live Sepolia records.** No agent has been published yet, so a run uses the clearly-')
  out.push('  labelled `dev-registry/registry.json` fallback unless the records exist.')
  out.push('  `npm run probe:registry` reports which strategy produced which names.')
  out.push('- **Live ENS subgraph enumeration.** The public ENS subgraph indexes mainnet names, so on')
  out.push('  Sepolia the `ens-subgraph` strategy is expected to return nothing. That is documented,')
  out.push('  not worked around.')
  out.push('- **A hosted model provider.** The routing decision needs a real OpenAI-compatible')
  out.push('  endpoint; unit tests inject a fake model and cover the full path with no network.')
  out.push('')
  out.push(`Overall: **${failed === 0 && missingDocs === 0 ? 'local gates green' : 'local gates NOT green'}**.`)
  out.push('')

  return out.join('\n')
}

async function main() {
  const startedAt = new Date().toISOString()
  const start = Date.now()

  console.log('')
  console.log(rule('='))
  console.log('  P3 repo-local gates  (no score, not the official harness)')
  console.log(rule('='))
  console.log('')

  const results = []
  for (const gate of GATES) {
    console.log(`  [run ] ${gate.id}`)
    const result = await run(gate.command)
    results.push({ id: gate.id, backs: gate.backs, ...result })
    console.log(`  [${result.ok ? 'pass' : 'FAIL'}] ${gate.id}  (${(result.durationMs / 1000).toFixed(1)} s)`)
    console.log('')
  }

  const docResults = REQUIRED_DOCS.map(([path, why]) => ({
    path,
    why,
    exists: existsSync(join(repoRoot, path)),
  }))

  console.log('  documents')
  for (const doc of docResults) {
    console.log(`  [${doc.exists ? 'ok  ' : 'MISS'}] ${doc.path}`)
  }
  console.log('')

  const failed = results.filter((r) => !r.ok)
  const missing = docResults.filter((d) => !d.exists)

  if (writeLog) {
    writeFileSync(logPath, renderLog(results, docResults, startedAt, Date.now() - start), 'utf8')
    console.log(`  written: ${logPath}`)
    console.log('')
  }

  if (failed.length === 0 && missing.length === 0) {
    console.log('  local gates green. No score is claimed and none is implied.')
    console.log('')
    return 0
  }

  console.log('  local gates NOT green:')
  for (const result of failed) console.log(`    - gate ${result.id} exited ${result.code ?? 'with an error'}`)
  for (const doc of missing) console.log(`    - missing ${doc.path}`)
  console.log('')
  return 1
}

main()
  .then((code) => {
    process.exit(code)
  })
  .catch((error) => {
    console.error('')
    console.error(`  harness:check failed: ${error instanceof Error ? error.message : String(error)}`)
    console.error('')
    process.exit(1)
  })