#!/usr/bin/env tsx
/**
 * `npm run record` — run every recorded routing case through the live route and write
 * `docs/routing-cases.md`.
 *
 * The recorded cases live in `src/shared/routing-cases.json` and state, for each client request,
 * the specific agent expected to handle it or an explicit `null`. This script turns those
 * expectations into observations: it calls the real route with the real model and the real
 * ENS-derived agent set, judges each result with the same rule the tests use, and rewrites the
 * document.
 *
 * What it needs: a reachable OpenAI-compatible model endpoint (`.env`) and, for a meaningful
 * run, published ENS records. With the development fallback active it will still run and still
 * produce a report — that report says so in every row, because an agent answered from the
 * fallback and not from ENS.
 *
 * Read-only: it sends no ENS transaction and never touches a wallet.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join, resolve as resolvePath } from 'node:path'
import { fileURLToPath } from 'node:url'

import { ConfigError, getConfig, type AppConfig } from '../src/server/config'
import { AgentDiscovery } from '../src/server/discovery'
import { createEnsClient } from '../src/server/ens'
import { routeRequest } from '../src/server/route'
import { AGENT_RECORD_KEYS, REGISTRY_RECORD_KEY } from '../src/shared/agent-record'
import { ROUTING_CASES, judgeRouteResult, type RoutingCase } from '../src/shared/routing-cases'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolvePath(here, '..')
const outPath = join(repoRoot, 'docs', 'routing-cases.md')

interface Observation {
  readonly testCase: RoutingCase
  readonly outcome: string
  readonly answeredAgent: string | null
  readonly decisionStatus: string
  readonly verdict: string
  readonly answerPreview: string | null
  readonly attributionHost: string | null
  readonly attributionSource: string | null
  readonly totalMs: number
  readonly error: string | null
}

function rule(char = '-'): string {
  return char.repeat(78)
}

function oneLine(value: string, max = 160): string {
  const flat = value.replace(/\s+/g, ' ').trim()
  return flat.length <= max ? flat : `${flat.slice(0, max - 1)}…`
}

async function observe(config: AppConfig, testCase: RoutingCase): Promise<Observation> {
  const client = createEnsClient(config.sepoliaRpcUrl, config.rpcTimeoutMs)
  const discovery = new AgentDiscovery(client, config)

  const result = await routeRequest({
    question: testCase.question,
    discovery,
    config,
    refreshFirst: true,
  })

  return {
    testCase,
    outcome: result.outcome,
    answeredAgent: result.attribution?.ensName ?? null,
    decisionStatus: result.routing.decisionStatus,
    verdict: result.routing.verdict,
    answerPreview: result.answer === null ? null : oneLine(result.answer),
    attributionHost: result.attribution?.endpointHost ?? null,
    attributionSource: result.attribution?.source ?? null,
    totalMs: result.totalDurationMs,
    error: result.error?.message ?? null,
  }
}

function render(observations: readonly Observation[], config: AppConfig): string {
  const passed = observations.filter((o) => judgeRouteResult(o.testCase, o).pass).length
  const routed = observations.filter((o) => o.attributionSource !== null)
  const usedDev = routed.some((o) => o.attributionSource === 'dev-registry')

  // Provenance is a three-way fact, not a boolean. Collapsing it to
  // `usedDev ? dev : live` made a run where *every* case errored — so no agent
  // was ever attributed — fall into the "live ENS records" branch and assert
  // live discovery that never happened. Only claim live discovery when at
  // least one case was actually attributed from a live ENS record.
  const provenance = (() => {
    if (routed.length === 0) {
      return '- **No case produced an agent attribution, so this run discovered nothing.** It demonstrates no ENS discovery and no routing.'
    }
    if (usedDev) {
      const n = routed.filter((o) => o.attributionSource === 'dev-registry').length
      return `- **${n} of ${observations.length} cases were answered by an agent from the labelled development fallback, not from ENS.** This run does not demonstrate live ENS discovery.`
    }
    return `- All ${routed.length} attributed cases were answered by an agent discovered from live ENS records.`
  })()

  const lines: string[] = []

  lines.push('# Recorded routing cases')
  lines.push('')
  lines.push('> Generated by `npm run record` (`scripts/record-routes.ts`).')
  lines.push('>')
  lines.push('> The expectations come from `src/shared/routing-cases.json`. The observations come from')
  lines.push('> running each case through the real route. Re-run this script whenever the record format,')
  lines.push('> the published records, the candidate set or the routing model changes — a routing change')
  lines.push('> that makes routing worse shows up here as a failing row.')
  lines.push('')
  lines.push(rule())
  lines.push('')
  lines.push(`- Problem: **${ROUTING_CASES.problem}** (\`${ROUTING_CASES.problemSlug}\`)`)
  lines.push(
    `- Discovery root this run: \`${config.agentDiscoveryRoot}\`` +
      ` (registry record \`${REGISTRY_RECORD_KEY}\`; expectations in \`routing-cases.json\` name \`${ROUTING_CASES.discoveryRoot}\`)`,
  )
  lines.push(`- Agent record keys: \`${AGENT_RECORD_KEYS.capability}\`, \`${AGENT_RECORD_KEYS.endpoint}\`, \`${AGENT_RECORD_KEYS.accepts}\``)
  lines.push(`- Routing model: \`${config.llmModel}\` at \`${new URL(config.llmBaseUrl).host}\``)
  lines.push(`- Model timeout: ${config.llmTimeoutMs} ms · downstream agent timeout: ${config.agentTimeoutMs} ms`)
  lines.push(`- Result: **${passed} of ${observations.length} cases matched their expected agent**`)
  lines.push(provenance)
  lines.push('')
  lines.push(rule())
  lines.push('')

  lines.push('## Cases')
  lines.push('')
  lines.push('| Case | Request | Expected | Observed | Outcome | Match |')
  lines.push('| --- | --- | --- | --- | --- | --- |')
  for (const observation of observations) {
    const verdict = judgeRouteResult(observation.testCase, observation)
    lines.push(
      `| \`${observation.testCase.id}\` | ${oneLine(observation.testCase.question, 90)} | \`${
        observation.testCase.expectAgent ?? 'no agent'
      }\` | \`${observation.answeredAgent ?? '—'}\` | \`${observation.decisionStatus}\` | ${verdict.pass ? '**yes**' : `**no** — ${verdict.detail}`} |`,
    )
  }
  lines.push('')

  lines.push('## Detail')
  lines.push('')
  for (const observation of observations) {
    const verdict = judgeRouteResult(observation.testCase, observation)
    lines.push(`### \`${observation.testCase.id}\` — ${verdict.pass ? 'matches' : 'does not match'}`)
    lines.push('')
    lines.push(`- **Request:** ${observation.testCase.question}`)
    lines.push(`- **Expected:** \`${observation.testCase.expectAgent ?? 'no agent'}\``)
    lines.push(`- **Why:** ${observation.testCase.why}`)
    lines.push(`- **Observed:** \`${observation.answeredAgent ?? 'no agent'}\` (\`${observation.outcome}\`, decision \`${observation.decisionStatus}\`)`)
    lines.push(`- **Router verdict:** ${observation.verdict}`)
    if (observation.attributionHost !== null) {
      lines.push(`- **Endpoint (from the agent's ENS record):** \`${observation.attributionHost}\` [source: \`${observation.attributionSource}\`]`)
    }
    lines.push(`- **Total route time:** ${observation.totalMs} ms`)
    if (observation.error !== null) lines.push(`- **Error:** ${observation.error}`)
    if (observation.answerPreview !== null) {
      lines.push(`- **Answer (first line):** ${observation.answerPreview}`)
    }
    if (!verdict.pass) lines.push(`- **Mismatch:** ${verdict.detail}`)
    lines.push('')
  }

  lines.push(rule())
  lines.push('')
  lines.push('## Reading this document')
  lines.push('')
  lines.push('- A row marked **no** is information, not noise. It is exactly the signal that a change made')
  lines.push('  routing worse, which is why the cases are recorded rather than improvised.')
  lines.push('- `no agent` expectations that pass are the router refusing to answer. A router that answered')
  lines.push('  every request would fail those rows, which is the point.')
  lines.push('- This document records one run. It is not a scored harness result and no score is claimed.')

  return `${lines.join('\n')}\n`
}

async function main(): Promise<number> {
  let config: AppConfig
  try {
    config = getConfig()
  } catch (error) {
    if (error instanceof ConfigError) {
      console.error(`\n${error.message}\n`)
      return 2
    }
    throw error
  }

  console.log('')
  console.log(rule('='))
  console.log('  Recording routing cases')
  console.log(rule('='))
  console.log('')
  console.log(`  model:  ${config.llmModel} at ${new URL(config.llmBaseUrl).host}`)
  console.log(`  root:   ${config.agentDiscoveryRoot}`)
  console.log(`  cases:  ${ROUTING_CASES.cases.length}`)
  console.log('')

  const observations: Observation[] = []

  for (const testCase of ROUTING_CASES.cases) {
    process.stdout.write(`  ${testCase.id} … `)
    try {
      const observation = await observe(config, testCase)
      observations.push(observation)
      const verdict = judgeRouteResult(testCase, observation)
      console.log(
        `${verdict.pass ? 'match  ' : 'MISMATCH'} → ${observation.answeredAgent ?? 'no agent'} (${observation.totalMs} ms)`,
      )
      if (!verdict.pass) console.log(`      ${verdict.detail}`)
    } catch (error) {
      console.log('ERROR')
      console.log(`      ${error instanceof Error ? error.message : String(error)}`)
      return 2
    }
  }

  writeFileSync(outPath, render(observations, config), 'utf8')

  const passed = observations.filter((o) => judgeRouteResult(o.testCase, o).pass).length

  console.log('')
  console.log(`  written: ${outPath}`)
  console.log(`  result:  ${passed} of ${observations.length} cases matched their expected agent`)
  console.log('')
  console.log('  This is a recorded demo run, not a scored harness result.')
  console.log('')

  // A check that cannot fail is not a check. Any mismatch — including a case
  // that errored because a dependency was unreachable — exits non-zero so a
  // broken run can never be mistaken for a passing one in CI or by hand.
  const mismatched = observations.length - passed
  if (mismatched > 0) {
    console.log(`  FAILED: ${mismatched} of ${observations.length} cases did not match.`)
    console.log('  docs/routing-cases.md was still written, and now records a failing run.')
    console.log('')
    return 1
  }
  return 0
}

process.exit(await main())